apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator-deployment
  labels:
    app: data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
        - name: data-generator
          # 替换为实际的镜像地址
          image: hub.hmf.xyz/base/data-generator:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          envFrom:
            - configMapRef:
                name: data-generator-config
---
apiVersion: v1
kind: Service
metadata:
  name: data-generator-service
spec:
  selector:
    app: data-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-generator-config
data:
  # 可添加应用需要的环境变量
  APP_ENV: "production"