apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator-realtime-deployment
  labels:
    app: data-generator-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator-realtime
  template:
    metadata:
      labels:
        app: data-generator-realtime
    spec:
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: hmfbd01
      containers:
        - name: data-generator
          # 替换为实际的镜像地址
          image: hub.hmf.xyz/base/data-generator-realtime:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 8000m
              memory: 4Gi
            requests:
              cpu: 4000m
              memory: 2Gi
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: logs-volume
          hostPath:
            path: /data2/generator-realtime-logs  # 宿主机上的存储路径，可按需修改
            type: DirectoryOrCreate