# 使用 OpenJDK 8 作为基础镜像
FROM openjdk:8-jre-slim-bullseye

ENV GENERATOR_HOME=/app
WORKDIR $GENERATOR_HOME

ADD target/data-generator $GENERATOR_HOME

# 创建目录用于存放日志和 dump 文件
RUN mkdir -p $GENERATOR_HOME/logs

# 运行数据生成器，启用 G1 垃圾收集器
#CMD ["java", "-XX:+UseG1GC", "-Xmx8g", "-Xms8g", "-XX:MaxGCPauseMillis=200", "-XX:InitiatingHeapOccupancyPercent=35", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/app/logs/heapdump.hprof", "-XX:+PrintGCDetails", "-XX:+PrintGCDateStamps", "-Xloggc:/app/logs/gc.log", "-cp", "data-generator-1.0-jar-with-dependencies.jar", "org.apdplat.data.generator.generator.Generator"]
# 运行数据生成器
CMD ["java", "-Xmx8g", "-Xms8g","-XX:NewSize=1g", "-XX:MaxNewSize=2g","-XX:+HeapDumpOnOutOfMemoryError","-XX:HeapDumpPath=logs/heapdump.hprof","-XX:+PrintGCDetails","-XX:+PrintGCDateStamps", "-XX:+PrintHeapAtGC", "-XX:+PrintTenuringDistribution", "-Xloggc:logs/gc.log","-cp", "conf:libs/*", "org.apdplat.data.generator.DataGeneratorApplication"]
# "-XX:+HeapDumpAfterFullGC"